package bootcamp.kcv2;

import java.util.ArrayList;

/** 
 *This class provides requested information
 *about answers which was made by student during tests.
 */

public class StudentAnswerSheet {
	
	String studentCode;
	String questionBundleName;
	ArrayList<String> answers;
	
	/**
	 * @return Unique code that was generated by linux command task 
	 * and user has registered it in database.
	 */
	public String getStudentCode() {
		return studentCode;
	}
	/**
	 * @param studentCode unique student code.
	 */
	public void setStudentCode(String studentCode) {
		this.studentCode = studentCode;
	}
	/**
	 * @return Questions theme.
	 */
	public String getQuestionBundleName() {
		return questionBundleName;
	}
	/**
	 * @param setName question theme that was sent by user which test he done.
	 */
	public void setQuestionBundleName(String setName) {
		this.questionBundleName = setName;
	}
	/**
	 * @return Answers which student made during test session.
	 */
	public ArrayList<String> getAnswers() {
		return answers;
	}
	/**
	 * @param answers which made student.
	 */
	public void setAnswers(ArrayList<String> answers) {
		this.answers = answers;
	}
}